"""Unique constrain __table_args__ added to Keyword model

Revision ID: 0ba7155b5287
Revises: 9b1f696b7d10
Create Date: 2025-10-18 19:40:02.240185

# https://testdriven.io/blog/fastapi-sqlmodel/#async-sqlmodel

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ba7155b5287'
down_revision: Union[str, Sequence[str], None] = '9b1f696b7d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'keyword', ['keywords', 'location_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'keyword', type_='unique')
    # ### end Alembic commands ###
