"""created_date row removed from Keyword model

Revision ID: 2a29d6a9daa4
Revises: 0ba7155b5287
Create Date: 2025-10-18 19:42:15.873945

# https://testdriven.io/blog/fastapi-sqlmodel/#async-sqlmodel

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a29d6a9daa4'
down_revision: Union[str, Sequence[str], None] = '0ba7155b5287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyword_created_date'), table_name='keyword')
    op.drop_column('keyword', 'created_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword', sa.Column('created_date', sa.DATE(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_keyword_created_date'), 'keyword', ['created_date'], unique=False)
    # ### end Alembic commands ###
