"""date value changed to datetime object

Revision ID: 880ee0eeffbc
Revises: e4bdfdfd5150
Create Date: 2025-10-03 15:59:56.505950

# https://testdriven.io/blog/fastapi-sqlmodel/#async-sqlmodel

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '880ee0eeffbc'
down_revision: Union[str, Sequence[str], None] = 'e4bdfdfd5150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keyword', 'date',
               existing_type=sa.INTEGER(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keyword', 'date',
               existing_type=sa.Date(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
