"""Location.location unique param has been reverted to True - service added to Keyword model

Revision ID: 9b1f696b7d10
Revises: 8e53cfd9c2a7
Create Date: 2025-10-18 19:33:26.113321

# https://testdriven.io/blog/fastapi-sqlmodel/#async-sqlmodel

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b1f696b7d10'
down_revision: Union[str, Sequence[str], None] = '8e53cfd9c2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword', sa.Column('service', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_keyword_service'), 'keyword', ['service'], unique=False)
    op.drop_index(op.f('ix_location_location'), table_name='location')
    op.create_index(op.f('ix_location_location'), 'location', ['location'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_location'), table_name='location')
    op.create_index(op.f('ix_location_location'), 'location', ['location'], unique=False)
    op.drop_index(op.f('ix_keyword_service'), table_name='keyword')
    op.drop_column('keyword', 'service')
    # ### end Alembic commands ###
