"""service removed - checked_date added to OrganicRank, created_date still under Keyword model v2 -  Keyword.keywords unique param  temporarely set to False

Revision ID: b21660f3e3ad
Revises: f35e90652e52
Create Date: 2025-10-18 17:56:03.537608

# https://testdriven.io/blog/fastapi-sqlmodel/#async-sqlmodel

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b21660f3e3ad'
down_revision: Union[str, Sequence[str], None] = 'f35e90652e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organicrank', sa.Column('checked_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_organicrank_checked_date'), 'organicrank', ['checked_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organicrank_checked_date'), table_name='organicrank')
    op.drop_column('organicrank', 'checked_date')
    # ### end Alembic commands ###
