"""date value changed to datetime object - v2

Revision ID: c09e1cff6d6e
Revises: 880ee0eeffbc
Create Date: 2025-10-03 16:25:12.033384

# https://testdriven.io/blog/fastapi-sqlmodel/#async-sqlmodel

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c09e1cff6d6e'
down_revision: Union[str, Sequence[str], None] = '880ee0eeffbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword', sa.Column('created_date', sa.Date(), nullable=False))
    op.drop_index(op.f('ix_keyword_date'), table_name='keyword')
    op.create_index(op.f('ix_keyword_created_date'), 'keyword', ['created_date'], unique=False)
    op.drop_column('keyword', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword', sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_keyword_created_date'), table_name='keyword')
    op.create_index(op.f('ix_keyword_date'), 'keyword', ['date'], unique=False)
    op.drop_column('keyword', 'created_date')
    # ### end Alembic commands ###
