"""initial schema

Revision ID: e4bdfdfd5150
Revises: 
Create Date: 2025-10-02 17:05:33.386095

# https://testdriven.io/blog/fastapi-sqlmodel/#async-sqlmodel

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4bdfdfd5150'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    op.create_index(op.f('ix_location_location'), 'location', ['location'], unique=False)
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_date'), 'keyword', ['date'], unique=False)
    op.create_index(op.f('ix_keyword_id'), 'keyword', ['id'], unique=False)
    op.create_index(op.f('ix_keyword_keywords'), 'keyword', ['keywords'], unique=False)
    op.create_table('organicrank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organicrank_id'), 'organicrank', ['id'], unique=False)
    op.create_index(op.f('ix_organicrank_link'), 'organicrank', ['link'], unique=False)
    op.create_index(op.f('ix_organicrank_position'), 'organicrank', ['position'], unique=False)
    op.create_index(op.f('ix_organicrank_source'), 'organicrank', ['source'], unique=False)
    op.create_index(op.f('ix_organicrank_title'), 'organicrank', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organicrank_title'), table_name='organicrank')
    op.drop_index(op.f('ix_organicrank_source'), table_name='organicrank')
    op.drop_index(op.f('ix_organicrank_position'), table_name='organicrank')
    op.drop_index(op.f('ix_organicrank_link'), table_name='organicrank')
    op.drop_index(op.f('ix_organicrank_id'), table_name='organicrank')
    op.drop_table('organicrank')
    op.drop_index(op.f('ix_keyword_keywords'), table_name='keyword')
    op.drop_index(op.f('ix_keyword_id'), table_name='keyword')
    op.drop_index(op.f('ix_keyword_date'), table_name='keyword')
    op.drop_table('keyword')
    op.drop_index(op.f('ix_location_location'), table_name='location')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
