"""service removed - checked_date added to OrganicRank, created_date still under Keyword model

Revision ID: f35e90652e52
Revises: 795bc3f9da1b
Create Date: 2025-10-18 17:51:24.999262

# https://testdriven.io/blog/fastapi-sqlmodel/#async-sqlmodel

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f35e90652e52'
down_revision: Union[str, Sequence[str], None] = '795bc3f9da1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_location'), table_name='location')
    op.create_index(op.f('ix_location_location'), 'location', ['location'], unique=True)
    op.add_column('organicrank', sa.Column('checked_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_organicrank_checked_date'), 'organicrank', ['checked_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organicrank_checked_date'), table_name='organicrank')
    op.drop_column('organicrank', 'checked_date')
    op.drop_index(op.f('ix_location_location'), table_name='location')
    op.create_index(op.f('ix_location_location'), 'location', ['location'], unique=False)
    # ### end Alembic commands ###
